### ISSUE TITLE
一括ソートのリクエスト

### ISSUE THREAD

**Issue by ShinoharaTa** [akiomik/nostr-matome#14]
postの投稿時間に従って、一括ソートのボタンがほしいです
時間順の昇順/降順 この２つがあるだけでも助かります

**Comment by akiomik** [comment]
en: This issue has been closed because I've added for sorting by "least recently created". About "recently created" I couldn't think of a use case, so I decide not to add it. This feature would be easy to add, so if you have a specific use case, please let me know by reopening this issue.

ja: 古い順でのソートに対応したのクローズしました。新しい順でのソートに関してはユースケースが思いつかなかったので見送りました。対応するのは簡単なので、もし具体的なユースケースがあればこのissueをreopenしてお知らせください。
